# Generated by Django 5.2.1 on 2025-05-13 10:58

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nrc_back',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='user',
            name='nrc_front',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.user_directory_path),
        ),
    ]
