# Generated by Django 5.2.1 on 2025-05-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_nrc_back_user_nrc_front_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('clients', 'Client'), ('loan_officer', 'Loan Officer'), ('region_manager', 'Region Manager'), ('manager', 'Manager'), ('superuser', 'Super User'), ('guarantor', 'Guarantor')], default='clients', max_length=20),
        ),
    ]
