# Generated by Django 5.2.1 on 2025-05-12 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grouploan',
            name='loan_officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmemberstatus',
            name='blocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmemberstatus',
            name='group_loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grouploan'),
        ),
        migrations.AddField(
            model_name='groupmemberstatus',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_member_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grouploan',
            name='members',
            field=models.ManyToManyField(related_name='group_loans', through='core.GroupMemberStatus', through_fields=('group_loan', 'member'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='individualloan',
            name='loan_officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='individualloan',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_loans_as_recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='groupmemberstatus',
            unique_together={('group_loan', 'member', 'frequency_letter')},
        ),
    ]
