# Generated by Django 5.2.1 on 2025-05-12 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouploan',
            name='time',
        ),
        migrations.RemoveField(
            model_name='individualloan',
            name='time',
        ),
    ]
