# Generated by Django 5.2.1 on 2025-05-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouploan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('overdue', 'Overdue'), ('completed', 'Completed')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='individualloan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('overdue', 'Overdue'), ('completed', 'Completed')], default='active', max_length=20),
        ),
    ]
