# Generated by Django 5.2.1 on 2025-05-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_grouploan_status_individualloan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouploan',
            name='time',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
