# Generated by Django 5.2.1 on 2025-05-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_collateral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouploan',
            name='time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
