# Generated by Django 5.2.1 on 2025-05-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_grouploan_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouploanpayment',
            name='payment_type',
            field=models.CharField(choices=[('ADVANCE', 'Advance Payment'), ('NORMAL', 'Normal Payment'), ('RECOVERY', 'Recovery Payment')], default='NORMAL', max_length=10),
        ),
        migrations.AddField(
            model_name='individualloanpayment',
            name='payment_type',
            field=models.CharField(choices=[('ADVANCE', 'Advance Payment'), ('NORMAL', 'Normal Payment'), ('RECOVERY', 'Recovery Payment')], default='NORMAL', max_length=10),
        ),
    ]
