# Generated by Django 5.2.1 on 2025-05-14 03:21

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0007_grouploanpayment_payment_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collateral',
            name='loan',
        ),
        migrations.RemoveField(
            model_name='collateral',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='collateral',
            name='video',
        ),
        migrations.AddField(
            model_name='collateral',
            name='collateral_type',
            field=models.CharField(choices=[('PHOTO', 'Photo'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collateral',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collateral',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collateral',
            name='file',
            field=models.FileField(default=1, upload_to=core.models.collateral_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collateral',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collateral',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_collaterals', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collateral',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collateral',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collateral',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_collaterals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='collateral',
            index=models.Index(fields=['content_type', 'object_id'], name='core_collat_content_93c826_idx'),
        ),
    ]
