# Generated by Django 5.2.1 on 2025-05-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_collateral_loan_remove_collateral_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouploan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Fixed interest rate percentage (e.g., 10.0 for 10%)', max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grouploan',
            name='repayment_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', help_text='How often payments are due', max_length=10),
        ),
        migrations.AddField(
            model_name='individualloan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Fixed interest rate percentage (e.g., 10.0 for 10%)', max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualloan',
            name='repayment_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', help_text='How often payments are due', max_length=10),
        ),
    ]
