# Generated by Django 5.2.1 on 2025-05-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_grouploan_interest_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collateral',
            name='collateral_type',
        ),
        migrations.AlterField(
            model_name='grouploan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='individualloan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=5),
        ),
    ]
