# Generated by Django 5.2.1 on 2025-05-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_collateral_collateral_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collateral',
            name='collateral_type',
            field=models.CharField(choices=[('PHOTO', 'Photo'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document')], default=1, help_text='Type of collateral being uploaded', max_length=10),
            preserve_default=False,
        ),
    ]
